{{- if eq (default "single" .Values.global.database.provider) "single" }}
{{- $user := required "global.config.databaseUser is required" .Values.global.config.databaseUser }}
{{- $password := required "global.secrets.databasePassword is required for single-db" .Values.global.secrets.databasePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgbouncer
  labels: {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: {{ (printf "\"%s\" \"%s\"\n" $user $password) | b64enc | quote }}
{{- end }}
