name: Code Coverage

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
        description: Component (backend, frontend), also used as path
      lcov_file:
        type: string
        required: true
        description: Relative path to lcov.info
      test_cmd:
        type: string
        required: true
        description: Command to run unit tests
    secrets:
      gh_token:
        required: true
        description: Default github token (secrets.GITHUB_TOKEN)

jobs:
  test:
    name: ${{ inputs.component }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm cache directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache coverage for static analysis
        uses: actions/cache@v3
        with:
          path: ${{ inputs.component }}/coverage
          key: coverage-${{ inputs.component }}-${{ github.run_number }}
          restore-keys: |
            coverage-${{ inputs.component }}-

      - name: Tests
        run: |
          cd ${{ inputs.component }}
          npm ci
          ${{ inputs.test_cmd }}

      - name: Report code coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          title: ${{ inputs.component }} coverage report
          delete-old-comments: true
          github-token: ${{ secrets.gh_token }}
          lcov-file: ./${{ inputs.lcov_file }}
