name: DEMO Route

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      target:
        description: 'PR number to receive DEMO URL routing'
        required: true
        type: number      

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  demo-routing:
    name: DEMO Routing
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'demo'
    env:
      DEST: demo
      DOMAIN: apps.silver.devops.gov.bc.ca
      REPO: ${{ github.event.repository.name }}
    runs-on: ubuntu-24.04
    steps:
      - name: Point DEMO URL to Existing Service
        uses: bcgov/action-oc-runner@v0.4.0
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          oc_server: ${{ vars.oc_server }}
          command: |
            oc delete route/${{ env.REPO }}-${{ env.DEST }} --ignore-not-found=true
            oc create route edge ${{ env.REPO }}-${{ env.DEST }} \
              --hostname=${{ env.REPO }}-${{ env.DEST }}.${{ env.DOMAIN }} \
              --service=${{ env.REPO }}-${{ github.event.number || inputs.target }}-frontend
